// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDGetter is an autogenerated mock type for the IDGetter type
type IDGetter struct {
	mock.Mock
}

type IDGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *IDGetter) EXPECT() *IDGetter_Expecter {
	return &IDGetter_Expecter{mock: &_m.Mock}
}

// GetID provides a mock function with given fields:
func (_m *IDGetter) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IDGetter_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type IDGetter_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *IDGetter_Expecter) GetID() *IDGetter_GetID_Call {
	return &IDGetter_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *IDGetter_GetID_Call) Run(run func()) *IDGetter_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDGetter_GetID_Call) Return(_a0 string) *IDGetter_GetID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDGetter_GetID_Call) RunAndReturn(run func() string) *IDGetter_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDGetter creates a new instance of IDGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDGetter {
	mock := &IDGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
