// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "ws-dummy-go/internal/dummy/domain"

	mock "github.com/stretchr/testify/mock"
)

// UsersKVRepo is an autogenerated mock type for the UsersKVRepo type
type UsersKVRepo struct {
	mock.Mock
}

type UsersKVRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersKVRepo) EXPECT() *UsersKVRepo_Expecter {
	return &UsersKVRepo_Expecter{mock: &_m.Mock}
}

// Set provides a mock function with given fields: ctx, name
func (_m *UsersKVRepo) Set(ctx context.Context, name string) (domain.UserID, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 domain.UserID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.UserID, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.UserID); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.UserID)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersKVRepo_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type UsersKVRepo_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *UsersKVRepo_Expecter) Set(ctx interface{}, name interface{}) *UsersKVRepo_Set_Call {
	return &UsersKVRepo_Set_Call{Call: _e.mock.On("Set", ctx, name)}
}

func (_c *UsersKVRepo_Set_Call) Run(run func(ctx context.Context, name string)) *UsersKVRepo_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UsersKVRepo_Set_Call) Return(_a0 domain.UserID, _a1 error) *UsersKVRepo_Set_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersKVRepo_Set_Call) RunAndReturn(run func(context.Context, string) (domain.UserID, error)) *UsersKVRepo_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name
func (_m *UsersKVRepo) Update(ctx context.Context, id domain.UserID, name string) error {
	ret := _m.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserID, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsersKVRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UsersKVRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.UserID
//   - name string
func (_e *UsersKVRepo_Expecter) Update(ctx interface{}, id interface{}, name interface{}) *UsersKVRepo_Update_Call {
	return &UsersKVRepo_Update_Call{Call: _e.mock.On("Update", ctx, id, name)}
}

func (_c *UsersKVRepo_Update_Call) Run(run func(ctx context.Context, id domain.UserID, name string)) *UsersKVRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserID), args[2].(string))
	})
	return _c
}

func (_c *UsersKVRepo_Update_Call) Return(_a0 error) *UsersKVRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UsersKVRepo_Update_Call) RunAndReturn(run func(context.Context, domain.UserID, string) error) *UsersKVRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsersKVRepo creates a new instance of UsersKVRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersKVRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersKVRepo {
	mock := &UsersKVRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
