linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - goimports
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - composites
      - shadow
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
      - (*github.com/ory/dockertest/v3.Resource).Expire

issues:
  exclude-dirs:
    - ./vendor
